#ifndef PREDFIT_H
#define PREDFIT_H

#include "types.h"

void predfit_init(AppState *state);
void predfit_refresh_work_dir(AppState *state);
int predfit_calculate(AppState *state);
/* Generate one catalogue for every configured species and present their
   concentration-weighted union as the prediction. */
int predfit_calculate_all_species(AppState *state);
int predfit_fit(AppState *state);
int predfit_undo_last_fit(AppState *state);
void predfit_publish_shared_state(AppState *state);
void predfit_adopt_shared_state(AppState *state);
void predfit_adopt_generated_catalog(AppState *state);
int predfit_restore_latest(AppState *state);

/* The session file: which spectra were open, which one was active, and the
   fit uncertainties the user chose. Save it whenever the working set changes. */
void predfit_load_session(AppState *state);
void predfit_save_session(AppState *state);
/* Guard against accidentally treating .fit/spectravisual.state as a two-column
   experimental spectrum: its numeric settings make it superficially valid. */
int predfit_is_session_file(const AppState *state, const char *path);
/* True only for the catalogue generated by the current Pred&Fit workspace.
   A manually opened .cat must keep the ordinary catalogue-only intensity
   path, even if a Pred&Fit calculation was run earlier in the session. */
int predfit_is_generated_catalog(const AppState *state, const char *path);
void predfit_open_advanced(AppState *state);
void predfit_close_advanced(AppState *state);
void predfit_dispose(AppState *state);
int predfit_handle_advanced_event(AppState *state, const SDL_Event *event);
void predfit_render_advanced(AppState *state);

#endif
