#ifndef PREDFIT_H
#define PREDFIT_H

#include "types.h"

void predfit_init(AppState *state);
void predfit_refresh_work_dir(AppState *state);
/* Project-level Hamiltonian selection.  The current editor continues to use
   PredFitState's active-model fields; these calls atomically store/load that
   projection so independent H settings never leak into each other. */
int predfit_hamiltonian_count(const AppState *state);
int predfit_active_hamiltonian_id(const AppState *state);
int predfit_add_hamiltonian(AppState *state, const char *name);
int predfit_duplicate_hamiltonian(AppState *state, const char *name);
/* Removes an H and every assignment that belongs to it. The final H of a
   project is protected, so a project always remains editable. */
int predfit_delete_hamiltonian(AppState *state, int index);
int predfit_select_hamiltonian(AppState *state, int index);
int predfit_calculate(AppState *state);
/* Generate one catalogue for every configured species and present their
   concentration-weighted union as the prediction. */
int predfit_calculate_all_species(AppState *state);
int predfit_fit(AppState *state);
int predfit_undo_last_fit(AppState *state);
void predfit_publish_shared_state(AppState *state);
void predfit_adopt_shared_state(AppState *state);
/* Recalculate the displayed catalogue without transferring any values between
   Intensity analysis and Pred&Fit.  Generated catalogues retain their
   per-species temperatures, dipoles and concentrations. */
void predfit_recompute_display_intensities(AppState *state);
void predfit_adopt_generated_catalog(AppState *state);
int predfit_restore_latest(AppState *state);
/* Persist only the temporary Fit choices. assignments.txt remains the
   authoritative, complete assignment list. */
int predfit_save_exclusions(AppState *state);
int predfit_load_exclusions(AppState *state);

/* The session file: which spectra were open, which one was active, and the
   fit uncertainties the user chose. Save it whenever the working set changes. */
void predfit_load_session(AppState *state);
void predfit_save_session(AppState *state);
/* Guard against accidentally treating .fit/spectravisual.state as a two-column
   experimental spectrum: its numeric settings make it superficially valid. */
int predfit_is_session_file(const AppState *state, const char *path);
/* True only for the catalogue generated by the current Pred&Fit workspace.
   A manually opened .cat must keep the ordinary catalogue-only intensity
   path, even if a Pred&Fit calculation was run earlier in the session. */
int predfit_is_generated_catalog(const AppState *state, const char *path);
void predfit_open_advanced(AppState *state);
void predfit_close_advanced(AppState *state);
void predfit_dispose(AppState *state);
int predfit_handle_advanced_event(AppState *state, const SDL_Event *event);
void predfit_render_advanced(AppState *state);

#endif
